# Net Outranking Flow
This module shows an example of how to use the “Net Outranking Flow” module.

In [1]:
%config Completer.use_jedi = False

## Definition of inputs and problem formalization

In [2]:
import random

import pandas as pd
from modular_parts.M9_NetOutrankingFlow import calculate_net_outranking_flows

alternatives = pd.Index([f"a{i}" for i in range(1, 10)])
profiles = pd.Index([f"r{i}" for i in range(1, 4)])
basic_outranking_flows = pd.DataFrame({'positive': [round(random.uniform(0, 1), 4) for i in range(1, 10)],
                                       'negative': [round(random.uniform(0, 1), 4) for i in range(1, 10)]},
                                      index=alternatives)

profile_based_inner_indexes = [profiles.append(pd.Index([a])) for a in alternatives]
profile_based_outer_indexes = ('R' + alternatives).to_list()
profile_based_outranking_flows = pd.concat([pd.DataFrame({
    'positive': [round(random.uniform(0, 1), 4) for i in range(1, 5)],
    'negative': [round(random.uniform(0, 1), 4) for i in range(1, 5)]},
    index=idx) for idx in profile_based_inner_indexes], keys=profile_based_outer_indexes)

In [3]:
basic_outranking_flows

    positive  negative
a1    0.7628    0.1454
a2    0.3410    0.2218
a3    0.9018    0.4713
a4    0.1306    0.2854
a5    0.2905    0.5277
a6    0.9631    0.2634
a7    0.8053    0.5020
a8    0.0620    0.0110
a9    0.6784    0.9556

In [4]:
profile_based_outranking_flows

        positive  negative
Ra1 r1    0.5518    0.8782
    r2    0.6417    0.3812
    r3    0.5404    0.9497
    a1    0.1784    0.4305
Ra2 r1    0.3956    0.0998
    r2    0.6771    0.6859
    r3    0.1311    0.3942
    a2    0.5683    0.6142
Ra3 r1    0.0996    0.0906
    r2    0.0242    0.8990
    r3    0.0085    0.9336
    a3    0.8700    0.0616
Ra4 r1    0.1692    0.9170
    r2    0.6347    0.6223
    r3    0.2391    0.0920
    a4    0.1099    0.9802
Ra5 r1    0.6307    0.6912
    r2    0.6383    0.5559
    r3    0.0759    0.4613
    a5    0.3572    0.7305
Ra6 r1    0.6497    0.8722
    r2    0.4936    0.6950
    r3    0.6475    0.9708
    a6    0.0735    0.0909
Ra7 r1    0.5755    0.8214
    r2    0.5878    0.3404
    r3    0.6420    0.6005
    a7    0.3409    0.0025
Ra8 r1    0.4551    0.0450
    r2    0.9950    0.9202
    r3    0.1997    0.0720
    a8    0.7966    0.6786
Ra9 r1    0.5085    0.3694
    r2    0.3279    0.1234
    r3    0.5063    0.3598
    a9    0.8906    0.6692

## Usage of Net flow

### Basic net flows

In [5]:
basic_net_flows = calculate_net_outranking_flows(basic_outranking_flows)
basic_net_flows

a1    0.6174
a2    0.1192
a3    0.4305
a4   -0.1548
a5   -0.2372
a6    0.6997
a7    0.3033
a8    0.0510
a9   -0.2772
dtype: float64

### Profile-based net flows

In [6]:
profile_based_net_flows = calculate_net_outranking_flows(profile_based_outranking_flows)
profile_based_net_flows

Ra1  r1   -0.3264
     r2    0.2605
     r3   -0.4093
     a1   -0.2521
Ra2  r1    0.2958
     r2   -0.0088
     r3   -0.2631
     a2   -0.0459
Ra3  r1    0.0090
     r2   -0.8748
     r3   -0.9251
     a3    0.8084
Ra4  r1   -0.7478
     r2    0.0124
     r3    0.1471
     a4   -0.8703
Ra5  r1   -0.0605
     r2    0.0824
     r3   -0.3854
     a5   -0.3733
Ra6  r1   -0.2225
     r2   -0.2014
     r3   -0.3233
     a6   -0.0174
Ra7  r1   -0.2459
     r2    0.2474
     r3    0.0415
     a7    0.3384
Ra8  r1    0.4101
     r2    0.0748
     r3    0.1277
     a8    0.1180
Ra9  r1    0.1391
     r2    0.2045
     r3    0.1465
     a9    0.2214
dtype: float64

You can also make this function add net flows as a "net" column. This type of output is needed for the FlowSort II method.

In [7]:
profile_based_net_flows_full = calculate_net_outranking_flows(profile_based_outranking_flows, True)
profile_based_net_flows_full

        positive  negative     net
Ra1 r1    0.5518    0.8782 -0.3264
    r2    0.6417    0.3812  0.2605
    r3    0.5404    0.9497 -0.4093
    a1    0.1784    0.4305 -0.2521
Ra2 r1    0.3956    0.0998  0.2958
    r2    0.6771    0.6859 -0.0088
    r3    0.1311    0.3942 -0.2631
    a2    0.5683    0.6142 -0.0459
Ra3 r1    0.0996    0.0906  0.0090
    r2    0.0242    0.8990 -0.8748
    r3    0.0085    0.9336 -0.9251
    a3    0.8700    0.0616  0.8084
Ra4 r1    0.1692    0.9170 -0.7478
    r2    0.6347    0.6223  0.0124
    r3    0.2391    0.0920  0.1471
    a4    0.1099    0.9802 -0.8703
Ra5 r1    0.6307    0.6912 -0.0605
    r2    0.6383    0.5559  0.0824
    r3    0.0759    0.4613 -0.3854
    a5    0.3572    0.7305 -0.3733
Ra6 r1    0.6497    0.8722 -0.2225
    r2    0.4936    0.6950 -0.2014
    r3    0.6475    0.9708 -0.3233
    a6    0.0735    0.0909 -0.0174
Ra7 r1    0.5755    0.8214 -0.2459
    r2    0.5878    0.3404  0.2474
    r3    0.6420    0.6005  0.0415
    a7    0.3409    0.0025  0.3384
Ra8 r1    0.4551    0.0450  0.4101
    r2    0.9950    0.9202  0.0748
    r3    0.1997    0.0720  0.1277
    a8    0.7966    0.6786  0.1180
Ra9 r1    0.5085    0.3694  0.1391
    r2    0.3279    0.1234  0.2045
    r3    0.5063    0.3598  0.1465
    a9    0.8906    0.6692  0.2214