# FlowSort GDSS
This module shows an example of how to use the "FlowSort GDSS" module.

## Definition of inputs and problem formalization

In [1]:
import pandas as pd
from modular_parts.preference import compute_preference_indices
from modular_parts.flows import calculate_gdss_flows
from modular_parts.sorting import calculate_flowsort_gdss_sorted_alternatives
from core.enums import Direction, GeneralCriterion, CompareProfiles


alternatives = [f"a{i}" for i in range(1, 8)]
profiles = [f"p{i}" for i in range(1, 4)]
criteria = [f"c{i}" for i in range(1, 4)]
dms = [f"DM_{i}" for i in range(1, 3)]
criteria_directions = pd.Series([Direction.MAX, Direction.MIN, Direction.MAX], index=criteria)
criteria_weights = pd.Series([0.3, 0.2, 0.5], index=criteria)
generalised_criteria = pd.Series([GeneralCriterion.U_SHAPE,
                                  GeneralCriterion.V_SHAPE_INDIFFERENCE,
                                  GeneralCriterion.USUAL], index=criteria)
preference_thresholds = pd.Series([2, 10, None], index=criteria)
indifference_thresholds = pd.Series([1, 5, None], index=criteria)
standard_deviations = pd.Series([None, None, None], index=criteria) # None, because we do not use GeneraCriterion.GAUSSIAN

alternatives_performances = pd.DataFrame([[15, 83, 21],
                                          [10, 90, 15],
                                          [11, 75, 20],
                                          [18, 59, 20],
                                          [17, 60, 28],
                                          [22, 44, 15],
                                          [13, 62, 22]], index=alternatives, columns=criteria)

DM_1_profiles_performances = pd.DataFrame([[12, 80, 16],
                                           [15, 68, 18],
                                           [18, 55, 20]], index=profiles, columns=criteria)
DM_2_profiles_performances = pd.DataFrame([[14, 75, 14],
                                           [15, 60, 17],
                                           [19, 50, 19]], index=profiles, columns=criteria)

all_profiles_performances = pd.concat([DM_1_profiles_performances, DM_2_profiles_performances], keys=dms)
all_profiles_performances_list = [DM_1_profiles_performances, DM_2_profiles_performances]

central_categories = [f"C{i}" for i in range(1, 4)]
boundary_categories = [f"C{i}" for i in range(1, 5)]

dms_weights = pd.Series([1, 1.2], index=dms)

## Required data

### Required preferences

In [2]:
_, DM_1_partial_altenatives_vs_profiles_preferences = compute_preference_indices(alternatives_performances,
                                                                                 preference_thresholds,
                                                                                 indifference_thresholds,
                                                                                 standard_deviations,
                                                                                 generalised_criteria,
                                                                                 criteria_directions,
                                                                                 criteria_weights,
                                                                                 DM_1_profiles_performances)

_, DM_2_partial_altenatives_vs_profiles_preferences = compute_preference_indices(alternatives_performances,
                                                                                 preference_thresholds,
                                                                                 indifference_thresholds,
                                                                                 standard_deviations,
                                                                                 generalised_criteria,
                                                                                 criteria_directions,
                                                                                 criteria_weights,
                                                                                 DM_2_profiles_performances)

_, all_profiles_partial_preferences = compute_preference_indices(all_profiles_performances,
                                                                 preference_thresholds,
                                                                 indifference_thresholds,
                                                                 standard_deviations,
                                                                 generalised_criteria,
                                                                 criteria_directions,
                                                                 criteria_weights)

In [3]:
DM_1_partial_altenatives_vs_profiles_preferences[0]

             p1   p2  p3
criteria
c1       a1   1  0.0   0
         a2   0  0.0   0
         a3   0  0.0   0
         a4   1  1.0   0
         a5   1  1.0   0
         a6   1  1.0   1
         a7   0  0.0   0
c2       a1   0  0.0   0
         a2   0  0.0   0
         a3   0  0.0   0
         a4   1  0.8   0
         a5   1  0.6   0
         a6   1  1.0   1
         a7   1  0.2   0
c3       a1   1  1.0   1
         a2   0  0.0   0
         a3   1  1.0   0
         a4   1  1.0   0
         a5   1  1.0   1
         a6   0  0.0   0
         a7   1  1.0   1

In [4]:
DM_1_partial_altenatives_vs_profiles_preferences[1]

             a1   a2   a3  a4  a5  a6   a7
criteria
c1       p1   0  1.0  0.0   0   0   0  0.0
         p2   0  1.0  1.0   0   0   0  1.0
         p3   1  1.0  1.0   0   0   0  1.0
c2       p1   0  1.0  0.0   0   0   0  0.0
         p2   1  1.0  0.4   0   0   0  0.0
         p3   1  1.0  1.0   0   0   0  0.4
c3       p1   0  1.0  0.0   0   0   1  0.0
         p2   0  1.0  0.0   0   0   1  0.0
         p3   0  1.0  0.0   0   0   1  0.0

In [5]:
DM_2_partial_altenatives_vs_profiles_preferences[0]

             p1  p2   p3
criteria
c1       a1   0   0  0.0
         a2   0   0  0.0
         a3   0   0  0.0
         a4   1   1  0.0
         a5   1   1  0.0
         a6   1   1  1.0
         a7   0   0  0.0
c2       a1   0   0  0.0
         a2   0   0  0.0
         a3   0   0  0.0
         a4   1   0  0.0
         a5   1   0  0.0
         a6   1   1  0.2
         a7   1   0  0.0
c3       a1   1   1  1.0
         a2   1   0  0.0
         a3   1   1  1.0
         a4   1   1  1.0
         a5   1   1  1.0
         a6   1   0  0.0
         a7   1   1  1.0

In [6]:
DM_2_partial_altenatives_vs_profiles_preferences[1]

              a1  a2  a3   a4   a5  a6  a7
criteria
c1       p1  0.0   1   1  0.0  0.0   0   0
         p2  0.0   1   1  0.0  0.0   0   1
         p3  1.0   1   1  0.0  1.0   0   1
c2       p1  0.6   1   0  0.0  0.0   0   0
         p2  1.0   1   1  0.0  0.0   0   0
         p3  1.0   1   1  0.8  1.0   0   1
c3       p1  0.0   0   0  0.0  0.0   0   0
         p2  0.0   1   0  0.0  0.0   1   0
         p3  0.0   1   0  0.0  0.0   1   0

In [7]:
all_profiles_partial_preferences

                 DM_1         DM_2
                   p1   p2 p3   p1   p2 p3
criteria
c1       DM_1 p1    0  0.0  0  0.0  0.0  0
              p2    1  0.0  0  0.0  0.0  0
              p3    1  1.0  0  1.0  1.0  0
         DM_2 p1    1  0.0  0  0.0  0.0  0
              p2    1  0.0  0  0.0  0.0  0
              p3    1  1.0  0  1.0  1.0  0
c2       DM_1 p1    0  0.0  0  0.0  0.0  0
              p2    1  0.0  0  0.4  0.0  0
              p3    1  1.0  0  1.0  0.0  0
         DM_2 p1    0  0.0  0  0.0  0.0  0
              p2    1  0.6  0  1.0  0.0  0
              p3    1  1.0  0  1.0  1.0  0
c3       DM_1 p1    0  0.0  0  1.0  0.0  0
              p2    1  0.0  0  1.0  1.0  0
              p3    1  1.0  0  1.0  1.0  1
         DM_2 p1    0  0.0  0  0.0  0.0  0
              p2    1  0.0  0  1.0  0.0  0
              p3    1  1.0  0  1.0  1.0  0

### Required flows

In [8]:
dms_partial_preferences = [DM_1_partial_altenatives_vs_profiles_preferences,
                           DM_2_partial_altenatives_vs_profiles_preferences]

alternatives_general_net_flows, profiles_general_net_flows = calculate_gdss_flows(
    dms_partial_preferences=dms_partial_preferences,
    dms_profile_vs_profile_partial_preferences=all_profiles_partial_preferences,
    criteria_weights=criteria_weights)

In [9]:
alternatives_general_net_flows

a1    0.296667
a2   -0.833333
a3    0.053333
a4    0.683333
a5    0.703333
a6    0.140000
a7    0.326667
dtype: float64

In [10]:
profiles_general_net_flows

               a1        a2        a3        a4        a5        a6        a7
DM_1 p1 -0.428571 -0.685714 -0.471429 -0.400000 -0.400000 -0.542857 -0.442857
     p2  0.037143 -0.148571  0.011429  0.131429  0.125714 -0.005714  0.028571
     p3  0.614286  0.471429  0.542857  0.614286  0.685714  0.614286  0.631429
DM_2 p1 -0.442857 -0.497143 -0.468571 -0.354286 -0.354286 -0.354286 -0.397143
     p2 -0.025714 -0.211429 -0.068571  0.045714  0.045714 -0.068571 -0.040000
     p3  0.500000  0.357143  0.500000  0.548571  0.500000  0.477143  0.500000

### Usage of FlowSort GDSS

### Central Profiles

In [11]:
first_step_assignments, final_step_assignments = \
    calculate_flowsort_gdss_sorted_alternatives(alternatives_general_net_flows,
                                                profiles_general_net_flows,
                                                central_categories,
                                                criteria_directions,
                                                all_profiles_performances_list,
                                                dms_weights,
                                                CompareProfiles.CENTRAL_PROFILES,
                                                True)

In [12]:
first_step_assignments

   worse better
a1    C2     C3
a2    C1     C1
a3    C2     C2
a4    C3     C3
a5    C3     C3
a6    C2     C2
a7    C2     C3

In [13]:
final_step_assignments

a1    C3
a2    C1
a3    C2
a4    C3
a5    C3
a6    C2
a7    C3
Name: better, dtype: object

### Boundary Profiles

In [14]:
first_step_assignments, final_step_assignments = \
    calculate_flowsort_gdss_sorted_alternatives(alternatives_general_net_flows,
                                                profiles_general_net_flows,
                                                boundary_categories,
                                                criteria_directions,
                                                all_profiles_performances_list,
                                                dms_weights,
                                                CompareProfiles.BOUNDARY_PROFILES,
                                                False)

In [15]:
first_step_assignments

   worse better
a1    C3     C3
a2    C1     C1
a3    C3     C3
a4    C4     C4
a5    C4     C4
a6    C3     C3
a7    C3     C3

In [16]:
final_step_assignments

a1    C3
a2    C1
a3    C3
a4    C4
a5    C4
a6    C3
a7    C3
Name: better, dtype: object