# Promethe Tri

This module shows an example of how to use the "Promethee Tri" module.

In [1]:
%config Completer.use_jedi = False

## Definition of inputs

In [2]:
import pandas as pd
import sys
sys.path.append('../..')

from modular_parts.sorting import calculate_prometheetri_sorted_alternatives

## Problem formalization

In [3]:
categories = [f"C{i}" for i in range(1, 4)]
criteria = [f"g{i}" for i in range(1, 6)]
alternatives = [f"a{i}" for i in range(1, 13)]
profiles = [f"r{i}" for i in range(1, 4)]

In [4]:
criteria_weights = pd.Series([0.283018867924528, 0.188679245283019, 0.188679245283019, 0.188679245283019, 0.150943396226415],
                     index=criteria)
criteria_weights

g1    0.283019
g2    0.188679
g3    0.188679
g4    0.188679
g5    0.150943
dtype: float64

In [5]:
g1_alternatives_profiles_preferences = pd.DataFrame([[1.0, 0.4, 0.0], [0.7, 0.0, 0.0], [0.5, 0.0, 0.0],
                                                     [0.5, 0.0, 0.0], [0.5, 0.0, 0.0], [1.0, 1.0, 0.0],
                                                     [1.0, 0.0, 0.0], [1.0, 0.6, 0.0], [1.0, 1.0, 0.2],
                                                     [0.5, 0.0, 0.0], [1.0, 0.0, 0.0], [1.0, 1.0, 0.2]],
                                                    index=alternatives, columns=profiles)

g2_alternatives_profiles_preferences = pd.DataFrame([[1.0, 0.3, 0.0], [0.8, 0.0, 0.0], [1.0, 0.2, 0.0],
                                                     [0.0, 0.0, 0.0], [1.0, 1.0, 0.5], [1.0, 0.5, 0.0],
                                                     [0.5, 0.0, 0.0], [1.0, 1.0, 0.0], [1.0, 0.5, 0.0],
                                                     [0.0, 0.0, 0.0], [1.0, 0.5, 0.0], [1.0, 1.0, 0.0]],
                                                    index=alternatives, columns=profiles)

g3_alternatives_profiles_preferences = pd.DataFrame([[1.0, 0.857142857142857, 0.0], [1.0, 1.0, 0.142857142857143],
                                                     [1.0, 1.0, 0.142857142857143], [0.714285714285714, 0.0, 0.0],
                                                     [1.0, 0.428571428571429, 0.0], [0.0, 0.0, 0.0],
                                                     [1.0, 0.428571428571429, 0.0], [1.0, 1.0, 0.0],
                                                     [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0],
                                                     [1.0, 1.0, 0.0]], index=alternatives, columns=profiles)

g4_alternatives_profiles_preferences = pd.DataFrame([[1.0, 0.999999999999987, 0.0], [1.0, 1.0, 0.864664716763387],
                                                     [1.0, 0.999999999999987, 0.0], [0.0, 0.0, 0.0],
                                                     [1.0, 1.0, 0.864664716763387], [0.0, 0.0, 0.0],
                                                     [1.0, 0.999999999999987, 0.0], [1.0, 1.0, 0.864664716763387],
                                                     [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0],
                                                     [1.0, 1.0, 0.864664716763387]],
                                                    index=alternatives, columns=profiles)

g5_alternatives_profiles_preferences = pd.DataFrame([[1.0, 1.0, 0.0], [0.166666666666667, 0.0, 0.0],
                                                     [1.0, 0.166666666666667, 0.0], [1.0, 0.0, 0.0],
                                                     [1.0, 1.0, 0.166666666666667], [1.0, 1.0, 0.0],
                                                     [1.0, 0.166666666666667, 0.0], [1.0, 1.0, 0.0],
                                                     [1.0, 1.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0],
                                                     [1.0, 1.0, 0.0]], index=alternatives, columns=profiles)

alterntives_vs_profiles_partial_preferences = pd.concat(
    [g1_alternatives_profiles_preferences, g2_alternatives_profiles_preferences,
     g3_alternatives_profiles_preferences, g4_alternatives_profiles_preferences,
     g5_alternatives_profiles_preferences], keys=criteria)

alterntives_vs_profiles_partial_preferences

              r1        r2        r3
g1 a1   1.000000  0.400000  0.000000
   a2   0.700000  0.000000  0.000000
   a3   0.500000  0.000000  0.000000
   a4   0.500000  0.000000  0.000000
   a5   0.500000  0.000000  0.000000
   a6   1.000000  1.000000  0.000000
   a7   1.000000  0.000000  0.000000
   a8   1.000000  0.600000  0.000000
   a9   1.000000  1.000000  0.200000
   a10  0.500000  0.000000  0.000000
   a11  1.000000  0.000000  0.000000
   a12  1.000000  1.000000  0.200000
g2 a1   1.000000  0.300000  0.000000
   a2   0.800000  0.000000  0.000000
   a3   1.000000  0.200000  0.000000
   a4   0.000000  0.000000  0.000000
   a5   1.000000  1.000000  0.500000
   a6   1.000000  0.500000  0.000000
   a7   0.500000  0.000000  0.000000
   a8   1.000000  1.000000  0.000000
   a9   1.000000  0.500000  0.000000
   a10  0.000000  0.000000  0.000000
   a11  1.000000  0.500000  0.000000
   a12  1.000000  1.000000  0.000000
g3 a1   1.000000  0.857143  0.000000
   a2   1.000000  1.000000  0.142857
   a3   1.000000  1.000000  0.142857
   a4   0.714286  0.000000  0.000000
   a5   1.000000  0.428571  0.000000
   a6   0.000000  0.000000  0.000000
   a7   1.000000  0.428571  0.000000
   a8   1.000000  1.000000  0.000000
   a9   0.000000  0.000000  0.000000
   a10  0.000000  0.000000  0.000000
   a11  0.000000  0.000000  0.000000
   a12  1.000000  1.000000  0.000000
g4 a1   1.000000  1.000000  0.000000
   a2   1.000000  1.000000  0.864665
   a3   1.000000  1.000000  0.000000
   a4   0.000000  0.000000  0.000000
   a5   1.000000  1.000000  0.864665
   a6   0.000000  0.000000  0.000000
   a7   1.000000  1.000000  0.000000
   a8   1.000000  1.000000  0.864665
   a9   0.000000  0.000000  0.000000
   a10  0.000000  0.000000  0.000000
   a11  0.000000  0.000000  0.000000
   a12  1.000000  1.000000  0.864665
g5 a1   1.000000  1.000000  0.000000
   a2   0.166667  0.000000  0.000000
   a3   1.000000  0.166667  0.000000
   a4   1.000000  0.000000  0.000000
   a5   1.000000  1.000000  0.166667
   a6   1.000000  1.000000  0.000000
   a7   1.000000  0.166667  0.000000
   a8   1.000000  1.000000  0.000000
   a9   1.000000  1.000000  0.000000
   a10  0.000000  0.000000  0.000000
   a11  0.000000  0.000000  0.000000
   a12  1.000000  1.000000  0.000000

In [6]:
g1_profiles_vs_alternatives = pd.DataFrame([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                                            [0.0, 0.8, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.5, 0.0],
                                            [0.6, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.4, 0.0, 1.0, 1.0, 0.0]],
                                           index=profiles, columns=alternatives)

g2_profiles_vs_alternatives = pd.DataFrame([[0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0],
                                            [0.0, 0.2, 0.0, 1.0, 0.0, 0.0, 0.5, 0.0, 0.0, 1.0, 0.0, 0.0],
                                            [0.7, 1.0, 0.8, 1.0, 0.0, 0.5, 1.0, 0.0, 0.5, 1.0, 0.5, 0.0]],
                                           index=profiles, columns=alternatives)

g3_profiles_vs_alternatives = pd.DataFrame([[0.0, 0.0, 0.0, 0.0, 0.0, 0.714285714285714, 0.0, 0.0,
                                             0.714285714285714, 0.0, 0.714285714285714, 0.0],
                                            [0.0, 0.0, 0.0, 0.285714285714286, 0.0, 1.0, 0.0, 0.0, 1.0,
                                             1.0, 1.0, 0.0],
                                            [0.571428571428571, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.285714285714286,
                                             1.0, 1.0, 1.0, 0.0]],
                                           index=profiles, columns=alternatives)

g4_profiles_vs_alternatives = pd.DataFrame([[0.0, 0.0, 0.0, 0.0, 0.0, 0.999999999977103, 0.0, 0.0,
                                             0.393469340287367, 0.988891003461758, 0.999999999977103, 0.0],
                                            [0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0],
                                            [0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0]],
                                           index=profiles, columns=alternatives)

g5_profiles_vs_alternatives = pd.DataFrame([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.166666666666667,
                                             0.0, 0.0],
                                            [0.0, 0.166666666666667, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0,
                                             0.0],
                                            [0.166666666666667, 1.0, 1.0, 1.0, 0.0, 0.166666666666667, 1.0,
                                             0.166666666666667, 0.0, 1.0, 1.0, 0.0]],
                                           index=profiles, columns=alternatives)

profiles_vs_alternatives_partial_preferences = pd.concat([g1_profiles_vs_alternatives, g2_profiles_vs_alternatives,
                                                          g3_profiles_vs_alternatives, g4_profiles_vs_alternatives,
                                                          g5_profiles_vs_alternatives], keys=criteria)
profiles_vs_alternatives_partial_preferences

             a1        a2   a3        a4   a5        a6   a7        a8  \
g1 r1  0.000000  0.000000  0.0  0.000000  0.0  0.000000  0.0  0.000000
   r2  0.000000  0.800000  1.0  1.000000  1.0  0.000000  0.0  0.000000
   r3  0.600000  1.000000  1.0  1.000000  1.0  0.000000  1.0  0.400000
g2 r1  0.000000  0.000000  0.0  0.200000  0.0  0.000000  0.0  0.000000
   r2  0.000000  0.200000  0.0  1.000000  0.0  0.000000  0.5  0.000000
   r3  0.700000  1.000000  0.8  1.000000  0.0  0.500000  1.0  0.000000
g3 r1  0.000000  0.000000  0.0  0.000000  0.0  0.714286  0.0  0.000000
   r2  0.000000  0.000000  0.0  0.285714  0.0  1.000000  0.0  0.000000
   r3  0.571429  0.000000  0.0  1.000000  1.0  1.000000  1.0  0.285714
g4 r1  0.000000  0.000000  0.0  0.000000  0.0  1.000000  0.0  0.000000
   r2  0.000000  0.000000  0.0  1.000000  0.0  1.000000  0.0  0.000000
   r3  0.000000  0.000000  0.0  1.000000  0.0  1.000000  0.0  0.000000
g5 r1  0.000000  0.000000  0.0  0.000000  0.0  0.000000  0.0  0.000000
   r2  0.000000  0.166667  0.0  0.000000  0.0  0.000000  0.0  0.000000
   r3  0.166667  1.000000  1.0  1.000000  0.0  0.166667  1.0  0.166667

             a9       a10       a11  a12
g1 r1  0.000000  0.000000  0.000000  0.0
   r2  0.000000  1.000000  0.500000  0.0
   r3  0.000000  1.000000  1.000000  0.0
g2 r1  0.000000  0.500000  0.000000  0.0
   r2  0.000000  1.000000  0.000000  0.0
   r3  0.500000  1.000000  0.500000  0.0
g3 r1  0.714286  0.000000  0.714286  0.0
   r2  1.000000  1.000000  1.000000  0.0
   r3  1.000000  1.000000  1.000000  0.0
g4 r1  0.393469  0.988891  1.000000  0.0
   r2  1.000000  1.000000  1.000000  0.0
   r3  1.000000  1.000000  1.000000  0.0
g5 r1  0.000000  0.166667  0.000000  0.0
   r2  0.000000  1.000000  1.000000  0.0
   r3  0.000000  1.000000  1.000000  0.0

In [7]:
g1_profiles_preferences = pd.DataFrame([[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [1.0, 1.0, 0.0]], index=profiles,
                                       columns=profiles)

g2_profiles_preferences = pd.DataFrame([[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [1.0, 1.0, 0.0]], index=profiles,
                                       columns=profiles)

g3_profiles_preferences = pd.DataFrame([[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [1.0, 1.0, 0.0]], index=profiles,
                                       columns=profiles)

g4_profiles_preferences = pd.DataFrame([[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [1.0, 1.0, 0.0]], index=profiles,
                                       columns=profiles)

g5_profiles_preferences = pd.DataFrame([[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [1.0, 1.0, 0.0]], index=profiles,
                                       columns=profiles)

profiles_partial_preferences = pd.concat([g1_profiles_preferences, g2_profiles_preferences, g3_profiles_preferences,
                                          g4_profiles_preferences, g5_profiles_preferences], keys=criteria)
profiles_partial_preferences

        r1   r2   r3
g1 r1  0.0  0.0  0.0
   r2  1.0  0.0  0.0
   r3  1.0  1.0  0.0
g2 r1  0.0  0.0  0.0
   r2  1.0  0.0  0.0
   r3  1.0  1.0  0.0
g3 r1  0.0  0.0  0.0
   r2  1.0  0.0  0.0
   r3  1.0  1.0  0.0
g4 r1  0.0  0.0  0.0
   r2  1.0  0.0  0.0
   r3  1.0  1.0  0.0
g5 r1  0.0  0.0  0.0
   r2  1.0  0.0  0.0
   r3  1.0  1.0  0.0

## Promethee Tri

In [8]:
promethee_tri = calculate_prometheetri_sorted_alternatives(categories, criteria_weights, 
                                                           (alterntives_vs_profiles_partial_preferences, 
                                                            profiles_vs_alternatives_partial_preferences),
                                                           profiles_partial_preferences, True, True)
promethee_tri

a1     C2
a2     C2
a3     C2
a4     C2
a5     C2
a6     C2
a7     C2
a8     C3
a9     C2
a10    C1
a11    C1
a12    C3
dtype: object